version: '3.9'
services:
  db:
    image: postgres
    container_name: taskboards_db
    ports:
      - '${DB_PORT}:${DB_PORT}'
    restart: always
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata:
